apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kafka-streams-job"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kafka-streams-job"
  template:
    metadata:
      labels:
        app: "kafka-streams-job"
    spec:
      containers:
        - name: "kafka-streams-job"
          image: 778851315920.dkr.ecr.us-east-1.amazonaws.com/kafka-streams-stateful-streaming-job
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
