apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: kafka-streams-benchmark
spec:
  sut:
    resources:
      - configMap:
          name: "kafka-streams-configmap"
          files:
            - "kafka-streams-deployment.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "load-generator-configmap"
          files:
            - "load-generator-deployment.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "kafka-streams-deployment.yaml"
  loadTypes:
    - typeName: "NumOfJobs"
      patchers:
        - type: "EnvVarPatcher"
          resource: "load-generator-deployment.yaml"
          properties:
            variableName: "NUM_OF_JOBS"
            container: "load-generator"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        consumerGroup: my-kafka-streams-app
        threshold: 3000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  kafkaConfig:
    bootstrapServer: "theodolite-kafka-kafka-bootstrap:9092"
    topics:
      - name: "input"
        numPartitions: 10
        replicationFactor: 1
      - name: "output"
        numPartitions: 1
        replicationFactor: 1
      - name: "my-kafka-streams-app-.*"
        removeOnly: True
