apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: kafka-streams-benchmark
spec:
  sut:
    resources:
      - configMap:
          name: "kafka-streams-configmap"
          files:
            - "service-account-rbca.yaml"
            - "kafka-streams-deployment.yaml"
  loadGenerator:
    resources:
      - configMap:
          name: "load-generator-configmap"
          files:
            - "service-account-rbca.yaml"
            - "load-generator-deployment.yaml"
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "kafka-streams-deployment.yaml"
  loadTypes:
    - typeName: "NumSensors"
      patchers:
        - type: "EnvVarPatcher"
          resource: "load-generator-deployment.yaml"
          properties:
            variableName: "NUM_SENSORS"
            container: "workload-generator"
        - type: "NumSensorsLoadGeneratorReplicaPatcher"
          resource: "load-generator-deployment.yaml"
          properties:
            loadGenMaxRecords: "150000"
  slos:
    - name: "lag trend"
      sloType: "lag trend"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        threshold: 3000
        externalSloUrl: "http://localhost:80/evaluate-slope"
        warmup: 60 # in seconds
  kafkaConfig:
    bootstrapServer: "theodolite-kafka-kafka-bootstrap:9092"
    topics:
      - name: "inbound-stream"
        numPartitions: 2
        replicationFactor: 1
      - name: "processed-stream"
        numPartitions: 1
        replicationFactor: 1
      - name: "theodolite-.*"
        removeOnly: True
