apiVersion: theodolite.rocks/v1beta1
kind: execution
metadata:
  name: theodolite-kafka-streams-execute
spec:
  benchmark: "kafka-streams-benchmark"
  load:
    loadType: "NumSensors"
    loadValues: [25000, 50000]
  resources:
    resourceType: "Instances"
    resourceValues: [1, 2]
  slos:
    - name: "lag trend"
      properties:
        threshold: 2000
  execution:
    metric: "demand"
    strategy:
      name: "RestrictionSearch"
      restrictions:
        - "LowerBound"
      searchStrategy: "LinearSearch"
    duration: 300 # in seconds
    repetitions: 1
    loadGenerationDelay: 30 # in seconds
