apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-balancer
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer