/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("ms.thesis.java-application-conventions")
    kotlin("jvm") version "1.8.20"
    kotlin("plugin.spring") version "1.8.20"
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    runtimeOnly("org.jetbrains.kotlin:kotlin-reflect:1.8.20")

    implementation("org.springframework.boot:spring-boot-starter-webflux:3.0.6")
//    implementation("org.apache.kafka:kafka-streams:3.4.0")
    implementation("org.springframework.cloud:spring-cloud-stream-binder-kafka-streams:4.0.2")
    implementation("io.projectreactor.kafka:reactor-kafka:1.3.17")
    implementation("org.springframework.kafka:spring-kafka:3.0.6")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.14.2")

    implementation("com.dynatrace.hash4j:hash4j:0.9.0")

    api(project(":common"))
}

application {
    // Define the main class for the application.
    mainClass.set("ms.thesis.log.state.LogStatePipelineApp")
}
