/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("ms.thesis.java-library-conventions")
}

dependencies {
    implementation("com.dynatrace.hash4j:hash4j:0.9.0")
}
