
nameOverride: "benchmarks-app"
fullnameOverride: "benchmarks-app"
appName: "benchmarks-app"

serviceAccount:
  create: true
  annotations: {}
  name: "benchmarks"


loadGenerator:
  name: "load-generator"

kafkaStreams:
  name: "kafka-streams"

apacheFlink:
  name: "apache-flink"

