apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.loadGenerator.name }}
          image: 778851315920.dkr.ecr.us-east-1.amazonaws.com/load-generator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: "NUM_OF_JOBS"
              value: "100"
            - name: "PERIOD"
              value: "1000"
            - name: "PARTITIONS"
              value: "1"
            - name: "TOPIC_REPLICATION_FACTOR"
              value: "1"
            - name: "SHOW_GENERATED_RECORDS"
              value: "false"
